export type Project={id:string;name:string;cat:string;a:string;b:string;overview:string;challenge:string;direction:string;delivered:string[]}
// Replace with real projects and screenshots. Current entries are illustrative concepts, not client results.
export const PROJECTS:Project[]=[
{id:'bagh',name:'Bagh',cat:'Restaurant',a:'#e8e6df',b:'#1d1d1b',overview:'A digital home for a garden restaurant built around menu, ambience and reservations.',challenge:'Communicate atmosphere before a guest arrives, without slowing the page.',direction:'Quiet, image-led, with slow reveals and a menu that reads like print.',delivered:['Website','Menu system','Reservation flow','Local SEO']},
{id:'bluepeak',name:'BluePeak',cat:'Real Estate',a:'#cfcfcc',b:'#111',overview:'A property showcase focused on clarity, trust and enquiries.',challenge:'Make complex listings scannable while feeling premium.',direction:'Architectural grids and directional motion that echoes floor plans.',delivered:['Listing pages','Search and filters','Lead forms','Google Ads landing pages']},
{id:'pitstop',name:'Pitstop Coffee',cat:'Coffee Shop',a:'#bdbdb9',b:'#0e0e0e',overview:'An energetic site for a neighbourhood coffee shop.',challenge:'Turn a fast, casual brand into an experience worth revisiting.',direction:'High-contrast type and kinetic marks with a playful rhythm.',delivered:['Website','Content strategy','Social templates','Ordering pages']},
{id:'garden',name:'Garden Padel',cat:'Sports Facilities',a:'#a9a9a5',b:'#0b0b0b',overview:'A booking-first website for a padel facility.',challenge:'Take players from curiosity to a booked court in a few taps.',direction:'Court geometry as visual language, with strong mobile ergonomics.',delivered:['Website','Booking journey','Meta Ads creative','Video content']},
{id:'luxe',name:'Luxe Jewellery',cat:'E-commerce',a:'#d8d8d4',b:'#151515',overview:'A refined online store for fine jewellery.',challenge:'Convey craft and value on screen while keeping checkout effortless.',direction:'Generous space and macro detail, with restrained motion.',delivered:['Store design','Product pages','Conversion optimisation','Ads and SEO']}]
export const CAPS:[string,string][]=[['Website Development','Premium websites, immersive experiences, e-commerce stores, and conversion-focused landing pages.'],['Meta & Google Ads','Performance-driven advertising designed to generate measurable business outcomes.'],['SEO','Technical and strategic search optimization that helps businesses build sustainable visibility.'],['Social Media & Content','Content strategy, creative direction, and social media management.'],['TikTok & YouTube Ads','Video-first campaigns that connect brands with relevant audiences.'],['E-commerce Growth','E-commerce strategy, store optimization, and Amazon PPC/FBA support.']]
export const SERVICES=CAPS.map(c=>c[0])
export const STEPS:[string,string][]=[['Discover','Understand the business, audience, and opportunity.'],['Define','Establish the creative direction, strategy, and structure.'],['Create','Design, develop, and refine the experience.'],['Launch','Deploy, measure, and continue improving.']]
